version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # Use Node.js image
    steps:
      - checkout  # Checkout the code from GitHub
      - run: echo "Building the application..."
      - run: npm install  # Install dependencies
      - run: npm test  # Run tests

  docker_build:
    docker:
      - image: docker:19.03.12  # Use Docker image
    steps:
      - checkout
      - setup_remote_docker  # Enable Docker commands
      - run:
          name: Build Docker Image
          command: docker build -t shazmaa/circleci-docker-project .
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASS | docker login -u shazmaa --password-stdin
      - run:
          name: Push Docker Image
          command: docker push shazmaa/circleci-docker-project

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
