version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.8
  
  sonar-executor:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
  
  dependency-executor:
    docker:
      - image: cimg/openjdk:17.0
  
  docker-executor-with-privileges:
    docker:
      - image: cimg/python:3.8-node
    resource_class: medium+

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Set up Virtual Environment
          command: |
            python -m venv venv
            . venv/bin/activate
            echo 'source venv/bin/activate' >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
            - venv

  sonar_scan:
    executor: sonar-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Create sonar-project.properties file
          command: |
            echo "sonar.projectKey=${SONAR_PROJECT_KEY}" > sonar-project.properties
            echo "sonar.organization=${SONAR_ORG}" >> sonar-project.properties
            echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
            echo "sonar.sources=." >> sonar-project.properties
            echo "sonar.python.coverage.reportPaths=coverage.xml" >> sonar-project.properties
            echo "sonar.branch.name=${CIRCLE_BRANCH}" >> sonar-project.properties
            echo "Contents of sonar-project.properties:"
            cat sonar-project.properties
      - run:
          name: Run SonarQube Analysis
          command: |
            if [ -n "${SONAR_TOKEN}" ]; then
              sonar-scanner -Dsonar.login=${SONAR_TOKEN}
            else
              echo "SONAR_TOKEN environment variable is not set. Skipping SonarQube scan."
              exit 1
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .scannerwork

    dependency_check:
    executor: dependency-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Dependency-Check
          command: |
            mkdir -p ~/dependency-check
            cd ~/dependency-check
            wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.5/dependency-check-9.0.5-release.zip
            unzip dependency-check-9.0.5-release.zip
            chmod +x ~/dependency-check/dependency-check/bin/dependency-check.sh
      - run:
          name: Run OWASP Dependency Check
          command: |
            mkdir -p reports
            ~/dependency-check/dependency-check/bin/dependency-check.sh \
              --scan ./ \
              --format "HTML" --out reports/dependency-report.html \
              --format "JSON" --out reports/dependency-report.json \
              --nvdApiKey=${NVD_API_KEY} \
              --failOnCVSS 7 \
              --connectionTimeout 600000
          no_output_timeout: 30m  # <-- This should be inside the `run` block properly indented
      - persist_to_workspace:
          root: .
          paths:
            - reports/dependency-report.html
            - reports/dependency-report.json

  unit_tests:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            pytest --junitxml=reports/unit-test-results.xml
      - persist_to_workspace:
          root: .
          paths:
            - reports/unit-test-results.xml

  docker_build:
    executor: docker-executor-with-privileges
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Docker Image
          command: |
            docker build -t ${DOCKERHUB_USERNAME}/${PROJECT_NAME}:latest .
      - run:
          name: Push to Docker Hub
          command: |
            echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker push ${DOCKERHUB_USERNAME}/${PROJECT_NAME}:latest

  email_reports:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Mail Utilities
          command: sudo apt-get update && sudo apt-get install -y mailutils
      - run:
          name: Send Email Report
          command: |
            if [ -n "${EMAIL_RECIPIENT}" ]; then
              echo "Sending reports to ${EMAIL_RECIPIENT}..."
              echo "Subject: CI/CD Report" > email.txt
              echo "SonarQube, Dependency Check, and Unit Test Reports Attached." >> email.txt
              echo "--------------------------------------" >> email.txt
              echo "SonarQube Results:" >> email.txt
              cat reports/sonarqube-report.txt >> email.txt
              echo "--------------------------------------" >> email.txt
              echo "Dependency Check Results:" >> email.txt
              cat reports/dependency-report.json >> email.txt
              echo "--------------------------------------" >> email.txt
              echo "Unit Test Results:" >> email.txt
              cat reports/unit-test-results.xml >> email.txt
              mail -s "CI/CD Pipeline Report" "${EMAIL_RECIPIENT}" < email.txt
            else
              echo "EMAIL_RECIPIENT is not set. Skipping email report."
              exit 1
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - sonar_scan:
          requires:
            - build
      - dependency_check:
          requires:
            - build
      - unit_tests:
          requires:
            - build
      - docker_build:
          requires:
            - sonar_scan
            - dependency_check
            - unit_tests
      - email_reports:
          requires:
            - sonar_scan
            - dependency_check
            - unit_tests
