version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11  # or change this to match your tech stack

jobs:
  checkout-code:
    executor: docker-executor
    steps:
      - checkout

  sonar-analysis:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=your-project-key \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

  dependency-check:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run OWASP Dependency Check
          command: |
            mkdir -p odc-reports
            dependency-check.sh \
              --project "MyApp" \
              --scan . \
              --out odc-reports \
              --format "HTML"

  unit-tests:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            pytest > test-results.txt

  docker-build-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t your-dockerhub-username/your-app:latest .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USER}" --password-stdin
            docker push your-dockerhub-username/your-app:latest

  send-email:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Send Security Reports via Email
          command: |
            apt-get update && apt-get install -y mailutils
            echo "Security Reports attached." | mail -s "DevSecOps Report" -A odc-reports/dependency-check-report.html -A test-results.txt your-email@example.com

workflows:
  devsecops-pipeline:
    jobs:
      - checkout-code
      - sonar-analysis:
          requires:
            - checkout-code
      - dependency-check:
          requires:
            - checkout-code
      - unit-tests:
          requires:
            - checkout-code
      - docker-build-push:
          requires:
            - unit-tests
            - dependency-check
            - sonar-analysis
      - send-email:
          requires:
            - docker-build-push
