version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  checkout-code:
    executor: docker-executor
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  sonar-analysis:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install SonarScanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner-cli-5.0.1.3006-linux.zip
            sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
            export PATH=$PATH:/opt/sonar-scanner/bin
            echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> $BASH_ENV
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORGANIZATION} \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

  dependency-check:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependency Check
          command: |
            mkdir -p ~/tools
            wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
            unzip dependency-check-8.4.0-release.zip -d ~/tools
            chmod +x ~/tools/dependency-check/bin/dependency-check.sh
            echo 'export PATH=$PATH:~/tools/dependency-check/bin' >> $BASH_ENV
      - run:
          name: Run OWASP Dependency Check
          command: |
            mkdir -p odc-reports
            ~/tools/dependency-check/bin/dependency-check.sh \
              --project "MyApp" \
              --scan . \
              --out odc-reports \
              --format "HTML"
      - persist_to_workspace:
          root: .
          paths:
            - odc-reports

  unit-tests:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run Unit Tests
          command: |
            mkdir -p test-results
            pytest --junitxml=test-results/junit.xml || true
            echo "Test execution complete" > test-results/test-summary.txt
      - persist_to_workspace:
          root: .
          paths:
            - test-results

  docker-build-push:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t ${DOCKERHUB_USER}/your-app:${CIRCLE_SHA1} .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USER}" --password-stdin
            docker push ${DOCKERHUB_USER}/your-app:${CIRCLE_SHA1}

  send-email:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install mail utilities
          command: |
            sudo apt-get update && sudo apt-get install -y mailutils
      - run:
          name: Send Security Reports via Email
          command: |
            echo "Security Reports attached." | mail -s "DevSecOps Report" \
              -A odc-reports/dependency-check-report.html \
              -A test-results/test-summary.txt ${NOTIFICATION_EMAIL}

workflows:
  devsecops-pipeline:
    jobs:
      - checkout-code
      - sonar-analysis:
          requires:
            - checkout-code
      - dependency-check:
          requires:
            - checkout-code
      - unit-tests:
          requires:
            - checkout-code
      - docker-build-push:
          requires:
            - unit-tests
            - dependency-check
            - sonar-analysis
      - send-email:
          requires:
            - docker-build-push
