version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Building the application..."
      - run: npm install
      - run: npm test

  docker_build:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t shazmaa/circleci-docker-project:latest .

  docker_push:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push Docker Image
          command: docker push shazmaa/circleci-docker-project:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
      - docker_push:
          requires:
            - docker_build
